name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Haskell Stack
      uses: haskell-actions/setup@v2
      with:
        stack-version: '2.13.1'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-
    
    - name: Install dependencies
      run: stack build --only-dependencies --test
    
    - name: Run tests
      run: stack test